#include "Debug/EFLogCategories.h"

DEFINE_LOG_CATEGORY(LogEFCore);
DEFINE_LOG_CATEGORY(LogEFNetwork);
DEFINE_LOG_CATEGORY(LogEFMovement);
DEFINE_LOG_CATEGORY(LogEFCombat);
DEFINE_LOG_CATEGORY(LogEFAI);
DEFINE_LOG_CATEGORY(LogEFSiege);
